# Machine learning course. Week 1

In [2]:
# import numpy as np
X = np.random.normal(loc=1, scale=10, size=(1000, 50))
print(X)

[[ 14.29463966   0.06958383  -1.81723015 ...   6.48278825 -12.36433426
    5.1449562 ]
 [  8.5386543   16.56718909 -19.82180529 ...   0.75221137   6.52410249
   -5.19706358]
 [-15.84394008  -0.96593772   6.33518703 ...   1.65722892   3.87627435
   12.11952155]
 ...
 [  3.5708801   -8.01011633  -3.79436787 ...  19.75262904  12.1321449
   18.83209106]
 [-10.51291321  -0.38320545  -1.46773297 ...  -1.758923    13.69918989
  -10.96979017]
 [ -7.93934395   4.63189849   5.87153013 ...   2.90413086  -6.24973095
  -12.51324895]]


In [4]:
m = np.mean(X, axis=0)
std = np.std(X, axis=0)
X_norm = ((X - m)  / std)
print(X_norm)

[[ 1.35850293 -0.05355007 -0.29762411 ...  0.61207811 -1.29945045
   0.35876768]
 [ 0.77715508  1.59942126 -2.07832198 ...  0.02755201  0.55022366
  -0.65073821]
 [-1.68545867 -0.15730376  0.50867049 ...  0.11986495  0.29093174
   1.0395694 ]
 ...
 [ 0.27541565 -0.86309258 -0.49316802 ...  1.96561865  1.09939833
   1.69479716]
 [-1.14703114 -0.09891712 -0.26305796 ... -0.22858687  1.25285319
  -1.21422597]
 [-0.88710363  0.40356932  0.46281366 ...  0.24705053 -0.70067017
  -1.36488616]]


In [6]:
Z = np.array([[4, 5, 0], 
             [1, 9, 3],              
             [5, 1, 1],
             [3, 3, 3], 
             [9, 9, 9], 
             [4, 7, 1]])

In [10]:
r = np.sum(Z, axis=1)
print(np.nonzero(r > 10))

(array([1, 4, 5]),)


In [11]:
A = np.eye(3)
B = np.eye(3)
print(A)
print(B)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
AB = np.vstack((A, B))
print(AB)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
import pandas
data = pandas.read_csv('week1/test.csv', index_col='PassengerId')

In [16]:
data[:10]

Pclass                                          Name     Sex  \
PassengerId                                                                 
892               3                              Kelly, Mr. James    male   
893               3              Wilkes, Mrs. James (Ellen Needs)  female   
894               2                     Myles, Mr. Thomas Francis    male   
895               3                              Wirz, Mr. Albert    male   
896               3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   
897               3                    Svensson, Mr. Johan Cervin    male   
898               3                          Connolly, Miss. Kate  female   
899               2                  Caldwell, Mr. Albert Francis    male   
900               3     Abrahim, Mrs. Joseph (Sophie Halaut Easu)  female   
901               3                       Davies, Mr. John Samuel    male   

              Age  SibSp  Parch     Ticket     Fare Cabin Embarked  
PassengerId                                                         
892          34.5      0      0     330911   7.8292   NaN        Q  
893          47.0      1      0     363272   7.0000   NaN        S  
894          62.0      0      0     240276   9.6875   NaN        Q  
895          27.0      0      0     315154   8.6625   NaN        S  
896          22.0      1      1    3101298  12.2875   NaN        S  
897          14.0      0      0       7538   9.2250   NaN        S  
898          30.0      0      0     330972   7.6292   NaN        Q  
899          26.0      1      1     248738  29.0000   NaN        S  
900          18.0      0      0       2657   7.2292   NaN        C  
901          21.0      2      0  A/4 48871  24.1500   NaN        S

In [18]:
data.head()

Pclass                                          Name     Sex  \
PassengerId                                                                 
892               3                              Kelly, Mr. James    male   
893               3              Wilkes, Mrs. James (Ellen Needs)  female   
894               2                     Myles, Mr. Thomas Francis    male   
895               3                              Wirz, Mr. Albert    male   
896               3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

              Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
PassengerId                                                       
892          34.5      0      0   330911   7.8292   NaN        Q  
893          47.0      1      0   363272   7.0000   NaN        S  
894          62.0      0      0   240276   9.6875   NaN        Q  
895          27.0      0      0   315154   8.6625   NaN        S  
896          22.0      1      1  3101298  12.2875   NaN        S

In [60]:
data['Pclass']

PassengerId
892     3
893     3
894     2
895     3
896     3
897     3
898     3
899     2
900     3
901     3
902     3
903     1
904     1
905     2
906     1
907     2
908     2
909     3
910     3
911     3
912     1
913     3
914     1
915     1
916     1
917     3
918     1
919     3
920     1
921     3
       ..
1280    3
1281    3
1282    1
1283    1
1284    3
1285    2
1286    3
1287    1
1288    3
1289    1
1290    3
1291    3
1292    1
1293    2
1294    1
1295    1
1296    1
1297    2
1298    2
1299    1
1300    3
1301    3
1302    3
1303    1
1304    3
1305    3
1306    1
1307    3
1308    3
1309    3
Name: Pclass, Length: 418, dtype: int64

In [23]:
data['Pclass'].value_counts()

3    218
1    107
2     93
Name: Pclass, dtype: int64

Задание на титанике

In [82]:
data_tit = pandas.read_csv('week1/titanic.csv', index_col='PassengerId')
data_tit.insert(3, 'First Name', '')
data_tit[::]

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   
6                   0       3   
7                   0       1   
8                   0       3   
9                   1       3   
10                  1       2   
11                  1       3   
12                  1       1   
13                  0       3   
14                  0       3   
15                  0       3   
16                  1       2   
17                  0       3   
18                  1       2   
19                  0       3   
20                  1       3   
21                  0       2   
22                  1       2   
23                  1       3   
24                  1       1   
25                  0       3   
26                  1       3   
27                  0       3   
28                  0       1   
29                  1       3   
30                  0       3   
...               ...     ...   
862                 0       2   
863                 1       1   
864                 0       3   
865                 0       2   
866                 1       2   
867                 1       2   
868                 0       1   
869                 0       3   
870                 1       3   
871                 0       3   
872                 1       1   
873                 0       1   
874                 0       3   
875                 1       2   
876                 1       3   
877                 0       3   
878                 0       3   
879                 0       3   
880                 1       1   
881                 1       2   
882                 0       3   
883                 0       3   
884                 0       2   
885                 0       3   
886                 0       3   
887                 0       2   
888                 1       1   
889                 0       3   
890                 1       1   
891                 0       3   

                                                          Name First Name  \
PassengerId                                                                 
1                                      Braund, Mr. Owen Harris              
2            Cumings, Mrs. John Bradley (Florence Briggs Th...              
3                                       Heikkinen, Miss. Laina              
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)              
5                                     Allen, Mr. William Henry              
6                                             Moran, Mr. James              
7                                      McCarthy, Mr. Timothy J              
8                               Palsson, Master. Gosta Leonard              
9            Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)              
10                         Nasser, Mrs. Nicholas (Adele Achem)              
11                             Sandstrom, Miss. Marguerite Rut              
12                                    Bonnell, Miss. Elizabeth              
13                              Saundercock, Mr. William Henry              
14                                 Andersson, Mr. Anders Johan              
15                        Vestrom, Miss. Hulda Amanda Adolfina              
16                            Hewlett, Mrs. (Mary D Kingcome)               
17                                        Rice, Master. Eugene              
18                                Williams, Mr. Charles Eugene              
19           Vander Planke, Mrs. Julius (Emelia Maria Vande...              
20                                     Masselmani, Mrs. Fatima              
21                                        Fynney, Mr. Joseph J              
22                                       Beesley, Mr. Lawrence              
23                                 McGowan, Miss. Anna "Annie"              
24      

In [35]:
# Подсчет мужчин и женщин
data_tit['Sex'].value_counts()

male      577
female    314
Name: Sex, dtype: int64

In [51]:
# Подсчет процентов выживших
data_tit['Survived'].value_counts(normalize=True)*100

0    61.616162
1    38.383838
Name: Survived, dtype: float64

In [50]:
# Подсчет доли пассажиров первого класса
data_tit['Pclass'].value_counts(normalize=True)*100

3    55.106622
1    24.242424
2    20.650954
Name: Pclass, dtype: float64

In [57]:
# Подсчет среднего и медианы возраста пассажиров
(data_tit['Age'].mean(), data_tit['Age'].median())

(29.69911764705882, 28.0)

In [58]:
# Подсчет корреляции родственников
data_tit.corr(method='pearson')

Survived    Pclass       Age     SibSp     Parch      Fare
Survived  1.000000 -0.338481 -0.077221 -0.035322  0.081629  0.257307
Pclass   -0.338481  1.000000 -0.369226  0.083081  0.018443 -0.549500
Age      -0.077221 -0.369226  1.000000 -0.308247 -0.189119  0.096067
SibSp    -0.035322  0.083081 -0.308247  1.000000  0.414838  0.159651
Parch     0.081629  0.018443 -0.189119  0.414838  1.000000  0.216225
Fare      0.257307 -0.549500  0.096067  0.159651  0.216225  1.000000

In [168]:
# Подсчет самого частого женского имени
femnames = data_tit.loc[data_tit.isin(['female']).any(axis=1)]['Name']
# print(femnames)
# i = 0
# for fn in femnames:
#     i += 1
#     print(i, fn.split('(')[1].split()[0].strip('()') if ('Mrs.' in fn) and ('(' in fn) else fn.split('.')[1].split()[0].strip('()'))
fnames = femnames.apply(lambda fn: fn.split('(')[1].split()[0].strip('()') if ('Mrs.' in fn) and ('(' in fn) else fn.split('.')[1].split()[0].strip('()'))
# fnames.value_counts()
type(femnames)
# data_tit['Name'][20].split('.').__getitem__(1).split().__getitem__(0)
# data_tit['First Name'] = data_tit['Name'].apply(lambda nm: nm.split('(')[1].split()[0])
# data_tit.loc[data_tit.isin(['female']).any(axis=1)]['First Name'].value_counts()
# data_tit.loc[data_tit.isin(['female']).any(axis=1)]
# print(femnames)
# data_tit[1:3]
type(fnames)
fnames.value_counts()

Anna          15
Mary          14
Elizabeth     11
Margaret      10
Alice          7
Bertha         5
Helen          5
Maria          5
Ellen          4
Ada            4
Catherine      4
Marie          4
Augusta        4
Annie          4
Marion         4
Emily          4
Florence       4
Katherine      3
Edith          3
Elisabeth      3
Kate           3
Lillian        3
Amelia         3
Ida            3
Jane           3
Madeleine      3
Hanora         3
Mathilde       2
Clara          2
Rosa           2
              ..
Velin          1
Josefine       1
Elina          1
Joan           1
Delia          1
Simonne        1
Anne           1
Harriet        1
Daisy          1
Sara           1
Miriam         1
Kristina       1
Irene          1
Marguerite     1
Hilda          1
Robina         1
Gretchen       1
Bessie         1
Gerda          1
Henriette      1
Eva            1
Fatima         1
Roberta        1
Eliza          1
Saiide         1
Clear          1
Katriina       1
Selini        

In [170]:
import numpy as np
from sklearn.tree import DecisionTreeClassifier
X = np.array([[1, 2], [3, 4], [5, 6]])
y = np.array([0, 1, 0])
clf = DecisionTreeClassifier()
clf.fit(X, y)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [194]:
importances = clf.feature_importances_
importances

array([0., 1.])

In [193]:
tmp = data_tit[['Pclass', 'Fare', 'Age', 'Sex', 'Survived']].dropna()
tmp['Sex'] = tmp['Sex'].apply(lambda sx: 1 if sx == 'male' else 0)
in_data = tmp[['Pclass', 'Fare', 'Age', 'Sex']]
out_trgt = tmp['Survived']
clf_surv = DecisionTreeClassifier()
clf_surv.fit(in_data, out_trgt)
importances = clf_surv.feature_importances_
importances

array([0.14000522, 0.30630826, 0.25317431, 0.30051221])